### PR TITLE
Add link to benchmarks

### PR DESCRIPTION
**Pull request by ahmadnassri**
consistently beats every other library!

### CODE REVIEW

**Comment by simov** [comment]
That's pretty impressive actually. I remember when I initially added https://github.com/ahmadnassri/benchmark-node-clone/pull/1 this module to your benchmark list and it wasn't anywhere near the fastest one.

I haven't changed anything in my code since then, and now it looks like deep-copy is multiple times faster than anyone else. Do you have any idea what may caused this change?

**Comment by ahmadnassri** [comment]
V8 internal improvements! I stopped testing anything before 4.x (since in a few days that would be the oldest LTS)

also, other libs sometimes took over on minor updates of Node / V8 (last time I checked was `component-clone` with early version of 7.x)

i'm actually working on a platform that will automate all this and would make it easier to have a breakdown per every version of node!

**Comment by simov** [comment]
I decided to run the benchmarks on my end:

```
  clone            x 12,092 ops/sec ±0.54% (87 runs sampled)
  clone-deep       x 12,094 ops/sec ±2.52% (78 runs sampled)
  clone-extend     x 10,544 ops/sec ±0.72% (91 runs sampled)
  cloneextend      x 21,024 ops/sec ±0.84% (92 runs sampled)
  component-clone  x 33,235 ops/sec ±0.59% (90 runs sampled)
  deep-copy        x 19,990 ops/sec ±0.59% (94 runs sampled)
  deepclone        x 11,200 ops/sec ±1.06% (91 runs sampled)
  deepcopy         x 12,907 ops/sec ±0.91% (91 runs sampled)
  extend           x 27,295 ops/sec ±0.60% (92 runs sampled)
  fast-clone       x 15,385 ops/sec ±1.07% (92 runs sampled)
  lodash.cloneDeep x 17,143 ops/sec ±0.73% (92 runs sampled)
  stringify-clone  x 30,592 ops/sec ±0.70% (91 runs sampled)
  structured-clone x 18,708 ops/sec ±0.69% (93 runs sampled)
  utils-copy       x  8,229 ops/sec ±0.90% (94 runs sampled)

Fastest is component-clone
Slowest is utils-copy
```

Obviously my computer is much slower than yours, but besides that I'm seeing a totally different picture.
I'm using Node v7.1.0

**Comment by simov** [comment]
@ahmadnassri you forgot to mention that the V8 fix was introduced in v7.2.1. I just tested with it and was I impressed .. `instanceof` FTW :grinning:

**Comment by ahmadnassri** [comment]
ah, yes, I just use `n` and switch versions with `n 7.` which just gets the latest.

this is presciently why I'm working on building a benchmarking automation platform, that allows people to test across versions, cpu profiles, and more!!! :smile:

**Comment by simov** [comment]
Yep, that would be nice. I'm using `nvm`

**Pull request merged**
